In [2]:
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4803, 7004, 8356, 1921],
 [4803, 7004, 8356, 1814],
 [4803, 5583, 8356, 1957],
 [9043, 3930, 7834, 8606, 6179],
 [9043, 3930, 7834, 8606, 2446],
 [321, 4803, 7798, 8356, 9214],
 [3093, 6568, 9786, 8606]]

In [8]:

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4803 7004 8356 1921]
 [   0    0    0    0 4803 7004 8356 1814]
 [   0    0    0    0 4803 5583 8356 1957]
 [   0    0    0 9043 3930 7834 8606 6179]
 [   0    0    0 9043 3930 7834 8606 2446]
 [   0    0    0  321 4803 7798 8356 9214]
 [   0    0    0    0 3093 6568 9786 8606]]


In [12]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 540ms/step


array([[[-0.03278039, -0.01864136,  0.00183004, -0.00027193,
         -0.01306176, -0.00478755,  0.03748845,  0.01151022,
          0.00587628,  0.01455555],
        [-0.03278039, -0.01864136,  0.00183004, -0.00027193,
         -0.01306176, -0.00478755,  0.03748845,  0.01151022,
          0.00587628,  0.01455555],
        [-0.03278039, -0.01864136,  0.00183004, -0.00027193,
         -0.01306176, -0.00478755,  0.03748845,  0.01151022,
          0.00587628,  0.01455555],
        [-0.03278039, -0.01864136,  0.00183004, -0.00027193,
         -0.01306176, -0.00478755,  0.03748845,  0.01151022,
          0.00587628,  0.01455555],
        [ 0.0484024 ,  0.00834309,  0.02554886, -0.04390248,
         -0.02340748, -0.02480841, -0.04368714,  0.03548609,
         -0.04377794, -0.02198323],
        [ 0.03371489, -0.0459412 ,  0.04267292,  0.03767539,
         -0.01391932,  0.04540611, -0.00586271,  0.03796245,
         -0.02392736,  0.03756774],
        [ 0.02589536, -0.04107224,  0.03640134,  0.0